### PR TITLE
Day 03 - Changed NMP to NPM(typo)

### PR DESCRIPTION
**Pull request by sycrw**
Just a small typo fixed.

### CODE REVIEW

**Review by lcarilla — APPROVED** [review]
yo what this is real?!?!?

**Review by momin-riyadh — APPROVED** [review]
Good Job!

**Review by ThomSullivan — APPROVED** [review]
NMP will not work when trying to use NPM, nice catch.

**Review by momin-riyadh — APPROVED** [review]
It Okay

**Pull request closed without merging**
